Project-Spring-2-Flying-Fisherman
CodeSoom/project-spring-2-Flying-Fisherman pull request #1
Opened 2021-06-28 15:39 UTC by Flying-Fisherman

이번 달 도 잘 부탁드립니다.

주제 정하기 힘드네요...

2021-06-29 12:04 UTC, johngrib reviewed
.gradle 이나 .idea처럼 커밋할 필요 없는 파일들이 많이 들어간 것 같아요.

2021-06-29 16:23 UTC, Flying-Fisherman commented
작성 중간에 Structure이 이상하게 설정되어 있어서 재설정 하는데 꽤나 애먹었습니다...
덕분에 Service 쪽을 간략하게 구성하고 TDD 식으로 해보려는데 오류가 나버려서 그제서야 잘못된걸 깨달아버렸네요

2021-06-30 15:07 UTC, johngrib commented
> 작성 중간에 Structure이 이상하게 설정되어 있어서 재설정 하는데 꽤나 애먹었습니다...
> 덕분에 Service 쪽을 간략하게 구성하고 TDD 식으로 해보려는데 오류가 나버려서 그제서야 잘못된걸 깨달아버렸네요

아쉬운 일이지만 이런 작은 일들도 경험이 될 거라 생각해보면 어떨까요 :-)

2021-06-30 15:08 UTC, johngrib commented on app/src/main/java/com/codesoom/scheduleMaker/application/ScheduleService.java
> +public class ScheduleService {
읽는 사람을 위한 JavaDoc을 잊지 말아주세요.

2021-07-01 12:10 UTC, johngrib reviewed
이 repository는 코드 리뷰 용도가 아니라 프로젝트 용도이기 때문에 PR 하나에 계속해서 커밋을 추가하지 않으셔도 됩니다. 작업별로 PR을 올리시고, 직접 머지하시는 방식으로 진행해 보세요.

2021-07-02 12:01 UTC, johngrib commented on app/src/test/java/com/codesoom/scheduleMaker/application/ScheduleServiceTest.java
> +    @Test
각 테스트에 설명이 없어서 어떤 테스트를 하고 있는지 한 눈에 알기가 어려워요.

2021-07-02 12:01 UTC, johngrib commented on app/src/main/java/com/codesoom/scheduleMaker/application/ScheduleService.java
> +     * @throws ScheduleNotFoundException 검색 조건에 맞는 Schedule이 없을 시 예외를 던집니다.
```suggestion
     * @throws ScheduleNotFoundException 검색 조건에 맞는 Schedule이 없을 경우
```

2021-07-02 12:01 UTC, johngrib commented on app/src/main/java/com/codesoom/scheduleMaker/application/ScheduleService.java
> +     * 식별자를 이용해 Schedule을 검색합니다.
```suggestion
     * 식별자를 이용해 Schedule을 검색해 리턴합니다.
```

2021-07-03 12:21 UTC, johngrib requested changes
`.idea`, `.gradle`은 관리 대상이 아니니 커밋하면 안됩니다. `.gitignore`에 추가하시고 `git rm`으로 삭제해주세요.

2021-07-04 12:11 UTC, johngrib reviewed
이 세가지 작업이 모두 하나의 커밋으로 만들어졌어요.
따로따로 커밋하는 연습이 필요해요.

![image](https://user-images.githubusercontent.com/1855714/124384448-43b1bd80-dd0c-11eb-9a84-eaeb81f7396e.png)

2021-07-05 13:29 UTC, hannut91 commented
작업이 완료되었다면, 머지 후 새로운 작업을 만들어주세요

2021-07-05 15:21 UTC, Flying-Fisherman commented
2가지 질문이 있습니다.

1.  Merge 부분은 제 Repo에서 진행하고 같은 Branch에서 계속 Commit 넣고 Merge하고 이어가는게 맞는지 궁금합니다.
Git도 그렇고 GitHub도 자연스럽게 굴려본 경험이 없어서 이 부분이 저에게 좀 애매합니다...

2. 이제 프론트도 구성해야하는데 이 전 강의에서 설명해주신 Marko를 꼭 이용해야 하는지 궁금합니다
(역시 경험 부재로 인해 사용법을 단시간에 익히기가 부담이 될거 같다고 생각됩니다)

2021-07-05 16:12 UTC, hannut91 commented
1. Merge 부분은 제 Repo에서 진행하고 같은 Branch에서 계속 Commit 넣고 Merge하고 이어가는게 맞는지 궁금합니다.
Git도 그렇고 GitHub도 자연스럽게 굴려본 경험이 없어서 이 부분이 저에게 좀 애매합니다...

=> 지금 레포에서 진행하고, 새로운 branch를 만들어서 작업을 완료한 후 `main` branch로 Merge하고 이어가는게 맞습니다. 그래서 하나의 풀리퀘스트가 하나의 작업이 되고, 이 작업을 위한 커밋들을 같이 올리고 머지합니다. 실무에서는 이렇게 작업이 진행됩니다. 처음에는 적응하는게 어려우실 수 있으나, 몇번 하다보면 익숙해져서 금방 배우실 수 있으실거에요. 

2. 편하신 것으로 진행하시면 됩니다! 리액트로 하신다면 제가 도와드릴 수 있습니다

2021-07-06 12:58 UTC, Flying-Fisherman commented
그럼 이 PR도 머지되면 새로 다시 올려야겠네요?

2021-07-06 13:51 UTC, hannut91 commented
맞습니다 ㅎㅎ 머지하고 새로운 브렌치를 만들어서 작업하고 푸시해서 새로운 풀 리퀘스트를 만드시면 됩니다!

2021-07-06 13:53 UTC, Flying-Fisherman commented
알겠습니다!

2021-07-10 13:38 UTC, merged